# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: nginx

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # Deploy to minikube server
    - name: Execute ssh command via using private key
      uses: appleboy/ssh-action@master
      with:
        #host: ${{ secrets.REMOTE_HOST }}
        host: 5daa09e5d31c.mylabserver.com
        username: cloud_user   
        #username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.CICD_SSH_KEY }}
        #port: ${{ secrets.PORT }}
        script: |
          rm -r /home/cloud_user/notejam-ops
          git clone --branch main https://github.com/hohuyhoangbk/notejam-ops.git
          cp notejam-ops/nginx/default /etc/nginx/sites-available/
          sudo nginx -t
          sudo nginx -s reload
          #helm upgrade notejam ./notejam-ops --set service.type=NodePort
